# `$ docker-compose up` in this directory to launch
version: "3"
services:
    asset_management_db:
        image: mysql
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: asset_management
        ports:
            - 3306:3306 # Access port: port in the container