# `$ docker-compose up` in this directory to launch
version: "3"
services:
    autotrader_db:
        image: mysql
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: autotrader
        ports:
            - 3307:3306 # Access port: port in the container